neox_user_cabinet:
    path:    /cabinet.html
    defaults: { _controller: NeoxUserBundle:Default:cabinet }

neox_user_login:
    path:    /login.html
    defaults: { _controller: NeoxUserBundle:Default:login }

neox_user_check_login:
    path:    /cabinet/check-login.html

neox_user_register:
    path:    /register.html
    defaults: { _controller: NeoxUserBundle:Default:register }

neox_user_registered:
    path:    /registered.html
    defaults: { _controller: NeoxUserBundle:Default:registered }

neox_user_logout:
    path:    /cabinet/logout.html
